// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: atom_ui

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_statusBar4 = lv_obj_create(ui_Screen6);
lv_obj_set_width( ui_statusBar4, 320);
lv_obj_set_height( ui_statusBar4, 18);
lv_obj_set_x( ui_statusBar4, 0 );
lv_obj_set_y( ui_statusBar4, 2 );
lv_obj_set_align( ui_statusBar4, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_statusBar4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_statusBar4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_statusBar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_statusBar4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_statusBar4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiMode4 = lv_label_create(ui_statusBar4);
lv_obj_set_width( ui_wifiMode4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiMode4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiMode4, 20 );
lv_obj_set_y( ui_wifiMode4, 0 );
lv_obj_set_align( ui_wifiMode4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wifiMode4,"STA");
lv_obj_set_style_text_font(ui_wifiMode4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiIcon4 = lv_img_create(ui_statusBar4);
lv_img_set_src(ui_wifiIcon4, &ui_img_wifi_closed_png);
lv_obj_set_width( ui_wifiIcon4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiIcon4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiIcon4, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_wifiIcon4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifiIcon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_atomLabel4 = lv_label_create(ui_statusBar4);
lv_obj_set_width( ui_atomLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_atomLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_atomLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_atomLabel4,"Flex-Ball Controller");
lv_obj_set_style_text_font(ui_atomLabel4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryIcon4 = lv_img_create(ui_statusBar4);
lv_img_set_src(ui_batteryIcon4, &ui_img_battery_png);
lv_obj_set_width( ui_batteryIcon4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryIcon4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryIcon4, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_batteryIcon4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batteryIcon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label31 = lv_label_create(ui_statusBar4);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -20 );
lv_obj_set_y( ui_Label31, 0 );
lv_obj_set_align( ui_Label31, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label31,"92%");
lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Screen6);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 267);
lv_obj_set_height( ui_Container4, 90);
lv_obj_set_x( ui_Container4, 0 );
lv_obj_set_y( ui_Container4, -20 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, -18 );
lv_obj_set_y( ui_Label30, 15 );
lv_label_set_text(ui_Label30,"SERVO 1");

ui_Slider1 = lv_slider_create(ui_Container4);
lv_slider_set_range(ui_Slider1, 0,180);
lv_slider_set_value( ui_Slider1, 90, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 6);
lv_obj_set_align( ui_Slider1, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label32 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, -18 );
lv_obj_set_y( ui_Label32, 15 );
lv_label_set_text(ui_Label32,"SERVO 2");

ui_Slider2 = lv_slider_create(ui_Container4);
lv_slider_set_range(ui_Slider2, 0,180);
lv_slider_set_value( ui_Slider2, 90, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider2)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider2, 150);
lv_obj_set_height( ui_Slider2, 6);
lv_obj_set_align( ui_Slider2, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 36);
lv_obj_set_x( ui_Button4, 60 );
lv_obj_set_y( ui_Button4, -20 );
lv_obj_set_align( ui_Button4, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label33 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"APPLY");
lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 36);
lv_obj_set_x( ui_Button5, -60 );
lv_obj_set_y( ui_Button5, -20 );
lv_obj_set_align( ui_Button5, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label34 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"CANCEL");

}
