// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: atom_ui

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_statusBar3 = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_statusBar3, 320);
lv_obj_set_height( ui_statusBar3, 18);
lv_obj_set_x( ui_statusBar3, 0 );
lv_obj_set_y( ui_statusBar3, 2 );
lv_obj_set_align( ui_statusBar3, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_statusBar3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_statusBar3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_statusBar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_statusBar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_statusBar3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiMode3 = lv_label_create(ui_statusBar3);
lv_obj_set_width( ui_wifiMode3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiMode3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiMode3, 20 );
lv_obj_set_y( ui_wifiMode3, 0 );
lv_obj_set_align( ui_wifiMode3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wifiMode3,"STA");
lv_obj_set_style_text_font(ui_wifiMode3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiIcon3 = lv_img_create(ui_statusBar3);
lv_img_set_src(ui_wifiIcon3, &ui_img_wifi_closed_png);
lv_obj_set_width( ui_wifiIcon3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiIcon3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiIcon3, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_wifiIcon3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifiIcon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_atomLabel3 = lv_label_create(ui_statusBar3);
lv_obj_set_width( ui_atomLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_atomLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_atomLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_atomLabel3,"Flex-Ball Controller");
lv_obj_set_style_text_font(ui_atomLabel3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryIcon3 = lv_img_create(ui_statusBar3);
lv_img_set_src(ui_batteryIcon3, &ui_img_battery_png);
lv_obj_set_width( ui_batteryIcon3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryIcon3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryIcon3, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_batteryIcon3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batteryIcon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label23 = lv_label_create(ui_statusBar3);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, -20 );
lv_obj_set_y( ui_Label23, 0 );
lv_obj_set_align( ui_Label23, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label23,"92%");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_Panel4, 116);
lv_obj_set_height( ui_Panel4, 174);
lv_obj_set_x( ui_Panel4, 20 );
lv_obj_set_y( ui_Panel4, 14 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label22, lv_pct(102));
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label22,"#2A82E4 PID #Parameters");
lv_label_set_recolor(ui_Label22,"true");
lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Panel4);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_height( ui_Container1, 40);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinbox3 = lv_spinbox_create(ui_Container1);
lv_obj_set_width( ui_Spinbox3, 80);
lv_obj_set_height( ui_Spinbox3, 36);
lv_obj_set_align( ui_Spinbox3, LV_ALIGN_RIGHT_MID );
lv_spinbox_set_digit_format( ui_Spinbox3, 4, 2);
lv_spinbox_set_range( ui_Spinbox3, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox3, 1 - 1);

ui_Label24 = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, 10 );
lv_obj_set_y( ui_Label24, -2 );
lv_obj_set_align( ui_Label24, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label24,"P");

ui_Container2 = lv_obj_create(ui_Panel4);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_height( ui_Container2, 40);
lv_obj_set_width( ui_Container2, lv_pct(100));
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinbox1 = lv_spinbox_create(ui_Container2);
lv_obj_set_width( ui_Spinbox1, 80);
lv_obj_set_height( ui_Spinbox1, 36);
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_RIGHT_MID );
lv_spinbox_set_digit_format( ui_Spinbox1, 4, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

ui_Label25 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, 10 );
lv_obj_set_y( ui_Label25, -2 );
lv_obj_set_align( ui_Label25, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label25,"I");

ui_Container3 = lv_obj_create(ui_Panel4);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_height( ui_Container3, 40);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinbox2 = lv_spinbox_create(ui_Container3);
lv_obj_set_width( ui_Spinbox2, 80);
lv_obj_set_height( ui_Spinbox2, 36);
lv_obj_set_align( ui_Spinbox2, LV_ALIGN_RIGHT_MID );
lv_spinbox_set_digit_format( ui_Spinbox2, 4, 2);
lv_spinbox_set_range( ui_Spinbox2, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox2, 1 - 1);

ui_Label26 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, 10 );
lv_obj_set_y( ui_Label26, -2 );
lv_obj_set_align( ui_Label26, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label26,"D");

ui_Button1 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_Button1, 140);
lv_obj_set_height( ui_Button1, 36);
lv_obj_set_x( ui_Button1, -20 );
lv_obj_set_y( ui_Button1, -23 );
lv_obj_set_align( ui_Button1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"START");
lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_Screen5);
lv_dropdown_set_options( ui_Dropdown2, "Position\nTrack\nTrace" );
lv_obj_set_width( ui_Dropdown2, 140);
lv_obj_set_height( ui_Dropdown2, 36);
lv_obj_set_x( ui_Dropdown2, -20 );
lv_obj_set_y( ui_Dropdown2, -25 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Label28 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label28, 130);
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, -26 );
lv_obj_set_y( ui_Label28, -64 );
lv_obj_set_align( ui_Label28, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label28,"Motion Type");

ui_Button3 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_Button3, 140);
lv_obj_set_height( ui_Button3, 36);
lv_obj_set_x( ui_Button3, -20 );
lv_obj_set_y( ui_Button3, 28 );
lv_obj_set_align( ui_Button3, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label29 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"SERVO SETTINGS");

}
